### ISSUE TITLE
Private Key record unnecessary?

### ISSUE THREAD

**Issue by toddherr** [smjones/draft-jones-dkim-key-wrapper#1]
I'm not clear on the need for a Private Key record, and I shudder to think of the security implications of shipping such precious data across the internet.

My understanding of this work was that it was focused on making publishing of public keys less mistake-prone, and inherent in my understanding is that the Key Generator will also be the Email Sender (and therefore the Email Signer). In that use case, there's no need to reveal the private key to anyone, even in an encoded state; the private key will be baked into the Email Sender's infrastructure, associated with the Domain Owner's account, and the Domain Owner need only ensure that the Public Key record make it to its destination, the DNS Operator.

**Comment by thevot** [comment]
Hi @toddherr :)
@smjones and I discussed this with similar concerns. 

The point is: scenarios exist where (please allow the blasphemy) private keys are shared. Or maybe "transferred" is a more appropriate term. Online generators that provide a pair of key, like [this one from socketlabs](https://tools.socketlabs.com/dkim/generator), also exist. 

The proposed document wants to cover also those scenarios so that the same logic (and format) can be applied to private keys if really needed.

**Comment by smjones** [comment]
In any event, this proposal should be considered deprecated in favor of broader solutions like Domain Connect. DC has considerably greater adoption than was apparent when this proposal was originally created.
